export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_TEAM = 'FETCHING_TEAM';
export const FETCHING_TEAM_FAILURE = 'FETCHING_TEAM_FAILURE';

export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_PEOPLE_SUCCESS = 'FETCHING_DATA_PEOPLE_SUCCESS';
export const FETCHING_DATA_TEAM_SUCCESS = 'FETCHING_DATA_TEAM_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const UPDATE_TWITTER_CONECTION = 'UPDATE_TWITTER_CONECTION';
export const UPDATE_TWITTER_PROFILE = 'UPDATE_TWITTER_PROFILE';
export const FETCHING_LOGGEDIN_DATA_SUCCESS = 'FETCHING_LOGGEDIN_DATA_SUCCESS';

export const FETCHING_DATA_CONTACT_SUCCESS = 'FETCHING_DATA_CONTACT_SUCCESS';
export const SET_CONTACT_PAGES = 'SET_CONTACT_PAGES';
export const SET_TEAM_PAGES = 'SET_TEAM_PAGES';
export const SET_PERSONAL_MESSAGES = 'SET_PERSONAL_MESSAGES';
export const SET_ALL_MEDIA = 'SET_ALL_MEDIA';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
