import {StyleSheet, Platform} from 'react-native';
import {colors} from '../../../services/utilities/colors/index';
import {width, height, totalSize} from 'react-native-dimension';
import {fontFamily, sizes} from '../../../services';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mainViewContainer: {
    flex: 1,
  },
  circle: {
    width: totalSize(1),
    height: totalSize(1),
    borderRadius: totalSize(1) / 2,
    backgroundColor: colors.statusBarColor,
  },
  line: {
    width: totalSize(0.3),
    height: height(6),
    backgroundColor: colors.statusBarColor,
  },
  blueButton: {
    width: Platform.OS == 'ios' ? totalSize(2.6) : totalSize(2.9),
    height: Platform.OS == 'ios' ? totalSize(2.6) : totalSize(2.9),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginRight: width(2),
    backgroundColor: colors.gradient1,
  },
  blueButtonLight: {
    // width: Platform.OS == 'ios' ? totalSize(6) : totalSize(2.9),
    // height: Platform.OS == 'ios' ? totalSize(2.6) : totalSize(2.9),
    paddingHorizontal: width(2),
    paddingVertical: height(0.8),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: colors.bgBlueLight,
  },
  inputContainer: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
    marginHorizontal: width(4),
    height: Platform.OS == 'ios' ? height(5) : height(7),
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: width(3),
  },
  saveButton: {
    width: width(20),
    height: Platform.OS == 'ios' ? height(3) : height(4),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.statusBarColor,
    borderRadius: 3,
  },
  addProduct: {
    width: width(31),
    height: Platform.OS == 'ios' ? height(3) : height(4),
    marginRight: width(3),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.statusBarColor,
    borderRadius: 3,
    flexDirection: 'row',
  },
  productCard: {
    // width: width(100),
    // paddingHorizontal: width(3),
    backgroundColor: colors.snow,
    width: width(92),
    paddingVertical: height(1),
    borderWidth: Platform.OS == 'ios' ? 0.4 : 1,
    borderColor: colors.borderLightColor,
    borderRadius: 5,
    alignSelf: 'center',
    marginTop: sizes.smallMargin,
  },
  productCardNew: {
    // width: width(100),
    flex: 1,
    marginLeft: width(4),
    marginRight: width(2),
    borderWidth: Platform.OS == 'ios' ? 0.5 : 1,
    borderColor: colors.borderLightColor,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: sizes.baseMargin,
    paddingVertical: height(1),
    backgroundColor: colors.snow,
  },
  textInput: {
    width: width(40),
    height: Platform.OS == 'ios' ? height(3) : height(4),
    backgroundColor: colors.snow,
    borderRadius: 2,
    paddingHorizontal: width(2),
    paddingVertical: 0,
    fontSize: totalSize(1.3),
  },
  blueButtonRemaining: {
    backgroundColor: colors.blueButtonBg,
    width: width(18),
    borderRadius: 3,
  },
  bottomContainer: {
    width: width(100),
    // paddingHorizontal: width(4),
  },
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: colors.bgLight,
  },
  alignCenter: {
    alignItems: 'center',
  },
  bottomNavBar: {
    width: width(100),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgLight,
    justifyContent: 'space-around',
    paddingVertical: totalSize(1.5),
    elevation: 5,
    marginTop: totalSize(5),
  },
  navBarText: {
    fontSize: totalSize(1.4),
    color: colors.textGrey,
    marginTop: totalSize(0.4),
  },
  productImageImge: {
    width: width(20),
    height: height(26),
    marginTop: totalSize(1.8),
  },
  iconStyle: {
    width: totalSize(3),
    height: totalSize(3),
  },
  imagesRowContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingTop: totalSize(0.5),
  },
  productContainer: {
    width: width(40),
    // height: height(50),
    backgroundColor: colors.snow,
    borderWidth: 1,
    borderColor: colors.steel, //textGrey
    borderRadius: 5,
    marginRight: totalSize(1.5),
    marginTop: totalSize(1),
    paddingHorizontal: totalSize(0.8),
    paddingVertical: totalSize(0.8),
  },
  addCartButton: {
    // paddingHorizontal: totalSize(2),
    width: totalSize(13),
    paddingVertical: totalSize(0.6),
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.gradient1,
    marginBottom: totalSize(0.4),
  },
  cartButtonText: {
    fontSize: totalSize(1.5),
    color: colors.snow,
  },
  productRegularText: {
    fontSize: totalSize(1.8),
    color: colors.textGrey,
    fontWeight: '800',
  },
  priceText: {
    fontSize: totalSize(2.1),
    fontWeight: 'bold',
    color: colors.textGrey,
  },
  categoryImge: {
    width: width(40),
    height: height(30),
    borderRadius: 15,
    marginRight: totalSize(1.5),
  },
  parentColorContainer: {
    flex: 1,
    width: width(100),
    backgroundColor: colors.blueBitLight,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.blueLighter,
  },
  serviceContainer: {
    flex: 1,
  },
  iconContainer: {
    borderRadius: 2,
    width: totalSize(3.5),
    height: totalSize(3.5),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.snow,
  },
  headerContainer: {
    width: width(100),
    backgroundColor: colors.greenLighter,
    borderBottomLeftRadius: totalSize(5),
    borderBottomRightRadius: totalSize(5),
    borderWidth: 1,
    borderColor: colors.greenBitLight,
  },
  headerText: {
    fontSize: totalSize(2.6),
    fontWeight: 'bold',
  },
  buttonText: {
    fontSize: totalSize(1.8),
  },
  viewAllButton: {
    borderWidth: 1,
    paddingVertical: totalSize(0.4),
    paddingHorizontal: totalSize(0.9),
    backgroundColor: colors.snow,
    borderColor: colors.gradient1,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryMainContainer: {
    // paddingVertical: totalSize(1.5),
    marginLeft: width(4),
    // alignSelf: 'center',
    // backgroundColor: 'red',
  },
  titleRowContainer: {
    // width: width(90),
    paddingRight: width(4),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bannerImage: {
    width: width(100),
    height: Platform.OS == 'ios' ? height(30) : height(38),
    justifyContent: null,
    paddingTop: Platform.OS == 'ios' ? height(3) : height(5),
    alignItems: 'flex-start',
  },
  row: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterContainer: {
    width: width(100),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: width(4),
    paddingVertical: height(2),
    backgroundColor: colors.snow,
  },
  simpleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  onlyRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputfieldStyle: {
    flex: 1,
    borderRadius: 10,
    paddingHorizontal: width(3),
  },
  fieldStyle: {
    backgroundColor: colors.silver,
    height: Platform.OS == 'ios' ? height(5) : height(6),
  },
  searchBarStyle: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: totalSize(2),
    backgroundColor: colors.snow,
    borderRadius: 10,
    paddingHorizontal: totalSize(1.3),
    height: height(6),
    // paddingVertical: totalSize(0.6),
  },
  prescriptionButton: {
    paddingHorizontal: totalSize(0.5),
    // paddingVertical: totalSize(0.5),
    height: totalSize(4),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  linearGradientwrap: {
    paddingHorizontal: totalSize(0.5),
    paddingVertical: totalSize(0.5),
    borderRadius: totalSize(5),
    height: totalSize(4.5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    height: totalSize(20),
    width: totalSize(30),
    borderRadius: 100,
    //marginTop: 350
  },
  searchContainer: {
    width: width(80),
    height: height(7),
    backgroundColor: colors.snow,
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: height(3),
    alignSelf: 'center',
    borderRadius: width(2),
    flexDirection: 'row',
    paddingHorizontal: width(2),
  },
  search: {
    backgroundColor: colors.snow,
    width: width(50),
    alignSelf: 'center',
  },
  headerText: {
    fontSize: height(2.5),
    color: colors.appColor1,
    marginLeft: width(3),
  },
  headerText1: {
    fontSize: height(1.5),
    color: colors.black,
    marginLeft: width(3),
  },
  flatListContainer: {
    width: width(90),
    height: height(10),
    borderRadius: height(2),
    backgroundColor: colors.snow,
    marginLeft: width(5),
    marginTop: height(1),
    elevation: 3,
    flexDirection: 'row',
    paddingHorizontal: width(2),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  image: {
    height: height(8),
    width: height(8),
    borderRadius: height(4),
    alignSelf: 'center',
  },
  flatListInnerContainer: {
    // alignItems: 'center',
    justifyContent: 'center',
    marginLeft: width(2),
    marginTop: totalSize(1),
  },
  smallBannerList: {
    width: width(30),
    height: Platform.OS == 'ios' ? height(14) : height(18),
    resizeMode: 'contain',
    marginHorizontal: width(1),
    // borderRadius: 5,
  },
  roundCategoryList: {
    width: totalSize(5), //width(13),
    height: totalSize(5), //Platform.OS == 'ios' ? height(6) : height(10),
    resizeMode: 'contain',
  },
  roundCategoryListContainer: {
    width: totalSize(5.5), //width(13),
    height: totalSize(5.5), //Platform.OS == 'ios' ? height(6) : height(10),
    borderRadius: totalSize(5.5) / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundCategoryMainContainer: {
    alignItems: 'center',
    marginHorizontal: width(2),
  },
  bigBanner: {
    width: width(100),
    height: Platform.OS == 'ios' ? height(12) : height(14),
    resizeMode: 'cover',
    // justifyContent: 'center',
  },
  oneLinerText: {
    color: colors.snow,
    textAlign: 'center',
    marginHorizontal: width(10),
    fontFamily: fontFamily.appTextBold,
  },
  servicesListContainer: {
    width: width(28),
    height: Platform.OS == 'ios' ? height(8) : height(10),
    justifyContent: 'center',
    paddingLeft: width(2),
    marginHorizontal: width(1.5),
    marginVertical: height(0.7),
    backgroundColor: colors.snow,
    borderRadius: 5,
  },
  personContainer: {
    width: width(92),
    flex: 1,
    alignSelf: 'center',
    paddingHorizontal: width(3),
    paddingVertical: height(3),
    backgroundColor: colors.snow,
    marginTop: height(2.5),
    borderWidth: 0.5,
    borderColor: colors.borderLightColor,
    borderRadius: 5,
  },
  radioButton: {
    width: Platform.OS == 'ios' ? totalSize(1.7) : totalSize(1.9),
    height: Platform.OS == 'ios' ? totalSize(1.7) : totalSize(1.9),
    borderRadius:
      Platform.OS == 'ios' ? totalSize(1.7) / 2 : totalSize(1.9) / 2,
    borderWidth: 1,
    borderColor: colors.textGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerRadioButton: {
    width: Platform.OS == 'ios' ? totalSize(1) : totalSize(1.3),
    height: Platform.OS == 'ios' ? totalSize(1) : totalSize(1.3),
    borderRadius: Platform.OS == 'ios' ? totalSize(1) / 2 : totalSize(1.3) / 2,
    // borderWidth: 0.5,
    // borderColor: colors.borderLightColor,
  },
});
export default styles;
